### ISSUE TITLE
can't copy instructions from the disassembly view

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-docs#152] opened 2016-02-15 06:30 UTC
sometimes i like to copy constants, or blocks of instructions to paste into scripts, or chat.

ida and radare2 allow for this, binary ninja only lets me copy an address

**Comment by CryptXor** [comment] 2016-02-15 07:24
https://github.com/Vector35/binaryninja-docs/issues/117

https://github.com/Vector35/binaryninja-docs/issues/91

**Comment by plafosse** [comment] 2016-02-27 05:31
This is a duplicate of #91

**Closed by plafosse** 2016-02-27 05:31 UTC
Labels: duplicate
