### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-docs#112] opened 2016-02-02 09:08 UTC
Been using binaryninja a lot these past few days, and something that I think would be a great addition is a simple bookmark manager to record addresses + comments :smile:

**Comment by psifertex** [comment] 2016-02-03 05:56
That's a good suggestion. We've been thinking about how to allow better tracking of location in other ways (cookie crumbs, etc), but a simple bookmark manager would be easy to implement.

**Comment by dfraze** [comment] 2016-02-05 04:42
Duplicate of issue 99?

**Comment by psifertex** [comment] 2016-02-06 01:34
Good catch.

**Closed by psifertex** 2016-02-06 01:34 UTC
Labels: enhancement
