### ISSUE TITLE
Some imports are not searchable in the names window

### ISSUE THREAD

**Issue by artemdinaburg** [Vector35/binaryninja-docs#119] opened 2016-02-05 02:43 UTC
Some imports are not searchable in the names list.

The import `tzset` is in the binary:
![image](https://cloud.githubusercontent.com/assets/1051838/12836545/f34d4ef4-cb87-11e5-86a6-72305957c015.png)

But `tzset` does not appear when you search for names:
![image](https://cloud.githubusercontent.com/assets/1051838/12836560/1cbeea5e-cb88-11e5-8a0d-b1f23286f5ae.png)

Other imports, such as `kill`, do show up:
![image](https://cloud.githubusercontent.com/assets/1051838/12836570/3de16432-cb88-11e5-878f-1f5ad5abdd8c.png)

**Comment by psifertex** [comment] 2016-02-05 02:45
This is actually a dupe of #115 though you've documented it better with examples and it might not have been immediately obvious it was the same so if nothing else, people who find this can head over there. I'm closing this one for now so we can track it in one place. Thanks for the submission.

**Closed by psifertex** 2016-02-05 02:45 UTC
