### ISSUE TITLE
Hex view goto offset enhancement

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-docs#107] opened 2016-02-01 16:23 UTC
It might be cool if hex view had a way to go to current address plus/minus value.

**Comment by psifertex** [comment] 2016-02-01 23:48
I think this is just #12, is it not?

**Comment by gynophage** [comment] 2016-02-02 00:30
Yeah, my bad.

**Comment by psifertex** [comment] 2016-02-02 03:14
No worries. Just making sure I wasn't missing a nuance of this one. Closing as dupe of #12

**Closed by psifertex** 2016-02-02 03:14 UTC
Labels: enhancement
