### ISSUE TITLE
layout engine places BBs in "interesting" location

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-docs#198] opened 2016-03-22 01:10 UTC
http://rghost.net/8SXNW5wKP <- firefox from ubuntu 15.10

go to `0x13fcb`

follow the "jne 0x13fd9", notice that the basic block is WAY off to the left, when it could be placed much closer (`xor rax, rax; retn`)

this is just one example of suboptimal routing, but i've seen it in other places.

**Comment by C0deH4cker** [comment] 2016-03-22 01:31
Duplicate of #58?

**Comment by psifertex** [comment] 2016-03-22 02:59
Not strictly a duplicate since #58 refers to just edges, but similar solution is planned for both. Layout bugs and edge routing bugs are going to get worked on after some other issues but definitely something we want to fix.

**Comment by plafosse** [comment] 2016-03-22 15:50
I'm going to mark this a duplicate since, we plan on doing a second pass on the node/edge layout. I will add a note #58 that it includes nodes as well as edges

**Closed by plafosse** 2016-03-22 15:50 UTC
Labels: duplicate
