### ISSUE TITLE
Data references to the null string not treated as strings

### ISSUE THREAD

**Issue by artemdinaburg** [Vector35/binaryninja-docs#120] opened 2016-02-05 02:50 UTC
Data references to the null string `{""}` are not detected and the values are treated as a constant:
![image](https://cloud.githubusercontent.com/assets/1051838/12836687/10dc29b2-cb89-11e5-8e1b-306ae293b149.png)

The highlighted line `mov qword [p3p], 0x412b35` should reference the null string (`{""}`), like the line above it references `{"UTF-8"}`, but the reference does not appear.

**Comment by psifertex** [comment] 2016-02-05 03:13
This one will be a long time before it's fixed (automatically at least) -- right now the system isn't generating propagating all type information (though there is a type system internally). Strings are detected heuristically. It's possible we could have a manual annotation that fixes it, but until then, this is really a subset of #121 so I'm going to mark it as a dupe of that.

**Closed** 2016-02-05 03:13 UTC
Labels: duplicate, enhancement
